services:
  mirror:
    image: ghcr.io/aminnez/maven-mirror:latest
    build:
      context: .
    restart: unless-stopped
    ports:
      - 9443:9443
    volumes:
      - ./config.yml:/home/app/config.yml
      - ./privkey.pem:/home/app/privkey.pem  
      - ./cert.pem:/home/app/cert.pem
      - ./local-cache:/home/app/local-cache